version: '2'

services:
  ruby:
    build: ./
    container_name: notifier
    volumes:
      - ./app/:/app
      - ./script/:/script
    environment:
      GITHUB_LOGIN_ID: Write Your Github Login ID
      GITHUB_PASSWORD: Write Your Github Password
      GITHUB_REPO: Write Your Repository
      SLACK_CHANNEL: Write Slack Channel Name
      SLACK_API_TOKEN: Write Your Slack Api Token
    command:
      - /script/start_app.sh
    tty: true

